volumes:
    app:

services:

    #######
    # App #
    #######

    app:
        volumes:
            # App
            - app:/srv/app

x-mutagen:
    sync:
        defaults:
            permissions:
                defaultFileMode: 0644
                defaultDirectoryMode: 0755
            configurationBeta:
                permissions:
                    defaultGroup: id:1000
                    defaultOwner: id:1000
        app:
            alpha: ../..
            beta: volume://app
            mode: two-way-resolved
