name: Integration
description: Integration
author: Elao

inputs:
  job:
    description: Job
    required: true
    default: ${{ github.job }}

runs:
  using: composite
  steps:

    - name: Setup
      uses: ./.manala/github/system
      with:
        setup: true
